# trigger:
# - master

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: FirstJob
  steps:
  - script: echo Job1
    displayName: 'run one-line script'
  - script: |
      echo add other task
      echo see https://google.com
      echo more info
    displayName: 'run mutli-line script'
- job: SecondJob
    dependsOn: Job1
  steps:
   - script: echo job2!
   displayName: 'run one-line script'
- job: Job3
    dependsOn: Job2
  steps:
    - script: echo Job3!
    displayName:  'run single line script'
- job: Job4
    dependsOn:
   - Job2
   - Job3
  steps:
    - script: echo Job4!
    displayName: 'run a single-line script'


      
